<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="STBlade.Modding.TLD.Il2CppAssemblies.Windows" Version="2.51.0" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Reflection" />
    <Using Include="HarmonyLib" />
    <Using Include="MelonLoader" />
    <Using Include="UnityEngine" />
  </ItemGroup>
</Project>
